### ISSUE TITLE
Crafter starts making bonemeal

### ISSUE THREAD

**Issue by AlexanderBeck0** [Rayzr522/Equilibria#1]
FITE ME M8

**Comment by foxfirecodes** [comment]
(ง •̀_•́)ง bring it on!

**Comment by AlexanderBeck0** [comment]
BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA BANANA
